require("turrets/eruptor/eruptor")
require("turrets/eruptor/magmator")
require("turrets/eruptor/hell")
require("turrets/minigun/minigun")
require("turrets/minigun/miinigun")
require("turrets/minigun/mivnigun")
require("turrets/tesla/tesla-i")
require("turrets/misc/blackhole")